export const ADD_SOURCE_WALLET = "ADD_SOURCE_WALLET";
export const ADD_DESTINATION_WALLET = "ADD_DESTINATION_WALLET";
export const CONNECT_WALLET_MODAL = "CONNECT_WALLET_MODAL";
export const UPDATE_TRANSACTION_STATUS = "UPDATE_TRANSACTION_STATUS";